actions = {
    "ORDER_FOOD": {"id": 1, "description": "Place an order for food delivery."},
    "FIND_RECIPE": {"id": 2, "description": "Search for cooking recipes based on ingredients or cuisine."},
    "ASK_HELP": {"id": 3, "description": "Request assistance or support."},
    "SHARE_NEWS": {"id": 4, "description": "Share the latest news or updates."},
    "BOOK_TAXI": {"id": 5, "description": "Book a ride or cab service."},
    "CHECK_WEATHER": {"id": 6, "description": "Get current weather information."},
    "SET_REMINDER": {"id": 7, "description": "Schedule a reminder for a task or event."},
    "PLAY_MUSIC": {"id": 8, "description": "Play a song, album, or playlist."},
    "SEND_EMAIL": {"id": 9, "description": "Compose and send an email."},
    "TRACK_ORDER": {"id": 10, "description": "Track delivery or order status."},
    "CALL_CONTACT": {"id": 11, "description": "Initiate a call to a saved contact."},
    "CREATE_EVENT": {"id": 12, "description": "Add an event to the calendar."},
    "CHECK_CALENDAR": {"id": 13, "description": "Review upcoming calendar events."},
    "GET_NEWS": {"id": 14, "description": "Fetch the latest news headlines."},
    "TRANSLATE_TEXT": {"id": 15, "description": "Translate text into another language."},
    "TELL_JOKE": {"id": 16, "description": "Tell a random or themed joke."},
    "DEFINE_WORD": {"id": 17, "description": "Provide the meaning of a word."},
    "CONVERT_UNITS": {"id": 18, "description": "Convert between different units of measurement."},
    "CALCULATE": {"id": 19, "description": "Perform a basic or scientific calculation."},
    "SEARCH_WEB": {"id": 20, "description": "Search the internet for information."},
    "READ_NOTIFICATIONS": {"id": 21, "description": "Read the latest app or system notifications."},
    "OPEN_APP": {"id": 22, "description": "Launch a specified application."},
    "GET_STOCK_PRICE": {"id": 23, "description": "Retrieve the latest stock market data."},
    "CHECK_FLIGHT_STATUS": {"id": 24, "description": "Look up current flight information."},
    "BOOK_HOTEL": {"id": 25, "description": "Make a hotel reservation."},
    "SEND_SMS": {"id": 26, "description": "Send a text message to a phone number."},
    "FIND_PLACE": {"id": 27, "description": "Locate a place on the map."},
    "GET_TIMEZONE": {"id": 28, "description": "Get the current time and timezone for a location."},
    "GENERATE_QR": {"id": 29, "description": "Generate a QR code from input data."},
    "SUMMARIZE_TEXT": {"id": 30, "description": "Summarize a block of input text."}
}
